### ISSUE TITLE
When press download zip there is no injector its just a bunch of dlls and visual studio stuff 

### ISSUE THREAD

**Issue by Lbruu** [DasJNNJ/Muck-Cheat#6]
![Screenshot 2021-06-10 062923](https://user-images.githubusercontent.com/85609810/121517639-3b888b80-c9b5-11eb-9092-a2b8a8fd5ea2.png)

**Comment by DasJNNJ** [comment]
You have to download the [Muck-Cheat-Injector](https://github.com/DasJNNJ/Muck-Cheat-Injector/).
